language: elixir
matrix:
  include:
    - otp_release: 18.2.1
      elixir: 1.3.2
    - otp_release: 18.3
      elixir: 1.4
    - otp_release: 19.3
      elixir: 1.4
    - otp_release: 20.0
      elixir: 1.4
    - otp_release: 19.3
      elixir: 1.5
    - otp_release: 20.0
      elixir: 1.5
    - otp_release: 20.0
      elixir: 1.6
env:
  global:
    - MIX_HOME=$(pwd)/.mix
script:
  - mix compile --warnings-as-errors
  - mix test
  - mix dialyze
  - mix format --check-formatted
cache:
  directories:
  - .mix
  - _build
