language: elixir
elixir:
  - 1.3.2
  - 1.4.0
otp_release:
  - 18.2.1
  - 19.1
env:
  global:
    - MIX_HOME=$(pwd)/.mix
script:
  - mix compile --warnings-as-errors
  - mix test
  - mix dialyze
cache:
  directories:
  - .mix
  - _build
